---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
hdfs:
  #superuser for hdfs
  superuser: ${hdfs.user:hdfs}
  #path on hdfs where broker creates dirs for user apps
  userspace.chroot: ${broker.userspace.path:/org/%{organization}/brokers/userspace/%{instance}}
  #encoded hadoop configuration files for hdfs
  provided.zip: ${hadoop.provided.zip:{}}
  #keytab for hdfs superuser, which will create encrypted zones
  keytab: ${hdfs.keytab:{}}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/hdfs}
  user: ${system.user}
  password: ${system.user.password}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:hdfs}
    serviceId: ${cf.catalog.serviceid:hdfs}
    serviceDescription: HDFS service for creating directories on hadoop distributed file system.
    baseId: ${BASE_GUID:}
    plans:
      - id: bare-plan
        name: bare
        description: bare
        free: true
        provisioning: false
      - id: shared-plan
        name: shared
        description: shared
        free: true
        provisioning: true
      - id: encrypted-plan
        name: encrypted
        description: encrypted
        free: true
        provisioning: true
      - id: multitenant-plan
        name: multitenant
        description: multitenant
        free: true
        provisioning: false
    metadata:
      imageUrl: ${IMAGE_URL:}
